name: Bright Data Trigger on Push

on:
  push:
    branches:
      - main  # Update if your main branch has a different name

jobs:
  run-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bright Data Trigger Script
        env:
          BRIGHTDATA_API_KEY: ${{ secrets.BRIGHTDATA_API_KEY }}
        run: python main.py

      - name: Send Slack Notification
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="✅ Success"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Failed"; fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS: *Push-triggered Bright Data job* ran on \`${{ github.ref_name }}\` by \`${{ github.actor }}\`.\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>\"}" \
            "$SLACK_WEBHOOK_URL"
