name: Daily Bright Data Trigger

on:
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC = 9 AM EST
  workflow_dispatch:  # Optional: allows manual triggering from GitHub UI

jobs:
  run-daily-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bright Data Trigger Script
        env:
          BRIGHTDATA_API_KEY: ${{ secrets.BRIGHTDATA_API_KEY }}
        run: python main.py

      - name: Send Slack Notification
        if: always()  # Change to `success()` to send only on success
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          STATUS="✅ Success"
          if [ "${{ job.status }}" != "success" ]; then STATUS="❌ Failed"; fi
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS: *Daily Bright Data Trigger* ran on \`${{ github.ref_name }}\` by \`${{ github.actor }}\`.\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>\"}" \
            "$SLACK_WEBHOOK_URL"
