name: Bright Data Trigger on Push

on:
  push:
    branches:
      - main  # Or the branch you want to watch

jobs:
  run-on-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run main.py
        run: python main.py
